USE DBMECANICA;

/* QUESTÃO 1*/
SELECT
	PROPRIETARIO.NOME
	, PROPRIETARIO.EMAIL
	, PROPRIETARIO.TELEFONE
FROM
	PROPRIETARIO
ORDER BY
	PROPRIETARIO.NOME;


/* QUESTÃO 2*/
SELECT
	SERVICO.NOME
	, SERVICO.VALOR
FROM
	SERVICO
ORDER BY
	SERVICO.NOME;


/* QUESTÃO 3*/
SELECT
	PRODUTO.NOME
	, PRODUTO.VALOR
FROM
	PRODUTO
ORDER BY
	PRODUTO.NOME;


/* QUESTÃO 4*/
SELECT
	VEICULO.MARCA
	, COUNT(VEICULO.IDVEICULO) AS QTDE
FROM
	VEICULO
GROUP BY
	 VEICULO.MARCA;


/* QUESTÃO 5*/
SELECT
	PROPRIETARIO.IDPROPRIETARIO
	, PROPRIETARIO.NOME
	, PROPRIETARIO.DT_NASCIMENTO
	, CASE WHEN DATE_ADD(PROPRIETARIO.DT_NASCIMENTO, INTERVAL YEAR(NOW()) - YEAR(PROPRIETARIO.DT_NASCIMENTO) YEAR) < NOW() THEN
			DATE_ADD(PROPRIETARIO.DT_NASCIMENTO, INTERVAL (YEAR(NOW()) - YEAR(PROPRIETARIO.DT_NASCIMENTO)) + 1 YEAR)
		ELSE
			DATE_ADD(PROPRIETARIO.DT_NASCIMENTO, INTERVAL YEAR(NOW()) - YEAR(PROPRIETARIO.DT_NASCIMENTO) YEAR)
		END AS NIVER
FROM
	PROPRIETARIO
WHERE
CASE WHEN DATE_ADD(PROPRIETARIO.DT_NASCIMENTO, INTERVAL YEAR(NOW()) - YEAR(PROPRIETARIO.DT_NASCIMENTO) YEAR) < NOW() THEN
			DATE_ADD(PROPRIETARIO.DT_NASCIMENTO, INTERVAL (YEAR(NOW()) - YEAR(PROPRIETARIO.DT_NASCIMENTO)) + 1 YEAR)
		ELSE
			DATE_ADD(PROPRIETARIO.DT_NASCIMENTO, INTERVAL YEAR(NOW()) - YEAR(PROPRIETARIO.DT_NASCIMENTO) YEAR)
		END BETWEEN NOW() AND DATE_ADD(NOW(), INTERVAL 45 DAY);


/* QUESTÃO 6*/
SELECT
	PROPRIETARIO.IDPROPRIETARIO
	, PROPRIETARIO.NOME
	, VEIVULO.IDVEICULO
	, VEICULO.MARCA
	, VEICULO.MODELO
	, VEICULO.PLACA
FROM
	PROPRIETARIO
	LEFT JOIN VEICULO ON
	VEICULO.IDPROPRIETARIO = PROPRIETARIO.IDPROPRIETARIO;


/* QUESTÃO 7*/
SELECT
	VEIVULO.IDVEICULO
	, VEICULO.MARCA
	, VEICULO.MODELO
	, VEICULO.PLACA
	, PROPRIETARIO.IDPROPRIETARIO
	, PROPRIETARIO.NOME
FROM
	VEICULO
	INNER JOIN PROPRIETARIO ON
	PROPRIETARIO.IDPROPRIETARIO  = VEICULO.IDPROPRIETARIO
ORDER BY
	PROPRIETARIO.NOME;


/* QUESTÃO 8*/
SELECT
	*
FROM
	MECANICO;


/* QUESTÃƒO 9*/
SELECT DISTINCT
	PRODUTO.NOME
	, PRODUTO.VALOR
FROM
	PRODUTO
	INNER JOIN ITEM_PRODUTO ON
	ITEM_PRODUTO.IDPRODUTO = PRODUTO.IDPRODUTO;


/* QUESTÃO 10*/
SELECT
	ORCAMENTO.IDORCAMENTO
	, ORCAMENTO.DATA
	, COUNT(SERVICO.IDSERVICO) AS QTDE_SERVICO
	, SUM(SERVICO.VALOR) AS VALOR_TOTAL_SERVICO
FROM
	VEICULO
	INNER JOIN ORCAMENTO ON
	ORCAMENTO.IDVEICULO = VEICULO.IDVEICULO
	LEFT JOIN ITEM_SERVICO ON
	ITEM_SERVICO.IDORCAMENTO = ORCAMENTO.IDOCARMENTO
	LEFT JOIN SERVICO ON 
	SERVICO.IDSERVICO = ITEM_SERVICO.IDSERVICO
WHERE
	VEICULO.IDVEICULO = 3
GROUP BY
	ORCAMENTO.IDORCAMENTO
	, ORCAMENTO.DATA;


/* QUESTÃO 11*/
SELECT
	ORCAMENTO.IDORCAMENTO
	, ORCAMENTO.DATA
	, COUNT(PRODUTO.IDPRODUTO) AS QTDE_PRODUTO
	, SUM(PRODUTO.VALOR) AS VALOR_TOTAL_PRODUTO
FROM
	VEICULO
	INNER JOIN ORCAMENTO ON
	ORCAMENTO.IDVEICULO = VEICULO.IDVEICULO
	LEFT JOIN ITEM_PRODUTO ON
	ITEM_PRODUTO.IDORCAMENTO = ORCAMENTO.IDORCAMENTO
	LEFT JOIN PRODUTO ON
	PRODUTO.IDPRODUTO = ITEM_PRODUTO.IDPRODUTO
WHERE
	VEICULO.IDVEICULO = 3
GROUP BY
	ORCAMENTO.IDORCAMENTO
	, ORCAMENTO.DATA;



/* QUESTÃO 12*/
SELECT
	ORCAMENTO.IDORCAMENTO
	, ORCAMENTO.DATA
	, MECANICO.IDMECANICO
	, MECANICO.NOME
FROM
	VEICULO
	INNER JOIN ORCAMENTO ON
	ORCAMENTO.IDVEICULO = VEICULO.IDVEICULO
	INNER JOIN MECANICO ON
	MECANICO.IDMECANICO = ORCAMENTO.IDMECANICO
WHERE
	VEICULO.IDVEICULO = 2;


/* QUESTÃO 13*/
SELECT
	VEICULO.IDVEICULO
	, VEICULO.MARCA
	, VEICULO.MODELO
	, VEICULO.PLACA
	, COUNT(ORCAMENTO.IDORCAMENTO) AS QTDE
FROM
	VEICULO
	INNER JOIN ORCAMENTO ON
	ORCAMENTO.IDVEICULO = VEICULO.IDVEICULO
WHERE
	VEICULO.ANO_FABRICACAO = 2014
GROUP BY
	VEICULO.IDVEICULO
	, VEICULO.MARCA
	, VEICULO.MODELO
	, VEICULO.PLACA;



/* QUESTÃO 14 - OPÇÃO A*/
SELECT 
	AVG(SOMA.TOTAL)
FROM
	(
		SELECT 
			VALORES.IDORCAMENTO
			, SUM(VALORES.TOTAL) AS TOTAL
		FROM 
			(
				SELECT 
					ITEM_SERVICO.IDORCAMENTO
					, SUM(ITEM_SERVICO.QTDE * SERVICO.VALOR) AS TOTAL
				FROM
					ITEM_SERVICO
					INNER JOIN SERVICO ON
					SERVICO.IDSERVICO = ITEM_SERVICO.IDSERVICO
				GROUP BY
					ITEM_SERVICO.IDORCAMENTO

				UNION ALL

				SELECT 
					ITEM_PRODUTO.IDORCAMENTO
					, SUM(ITEM_PRODUTO.QTDE * PRODUTO.VALOR) AS TOTAL
				FROM
					ITEM_PRODUTO
					INNER JOIN PRODUTO ON
					PRODUTO.IDPRODUTO = ITEM_PRODUTO.IDPRODUTO
				GROUP BY
					ITEM_PRODUTO.IDORCAMENTO
			) AS VALORES
		GROUP BY
			VALORES.IDORCAMENTO
	) AS SOMA
;


/* QUESTÃO 14 - OPÇÃO B*/
SELECT
	AVG(
		(SELECT 
			SUM(ITEM_SERVICO.QTDE * SERVICO.VALOR) AS TOTAL
		FROM
			ITEM_SERVICO
			INNER JOIN SERVICO ON
			SERVICO.IDSERVICO = ITEM_SERVICO.IDSERVICO
		WHERE 
			ITEM_SERVICO.IDORCAMENTO = ORCAMENTO.IDORCAMENTO
		GROUP BY
			ITEM_SERVICO.IDORCAMENTO)
	+ 	(SELECT 
			SUM(ITEM_PRODUTO.QTDE * PRODUTO.VALOR) AS TOTAL
		FROM
			ITEM_PRODUTO
			INNER JOIN PRODUTO ON
			PRODUTO.IDPRODUTO = ITEM_PRODUTO.IDPRODUTO
		WHERE 
			ITEM_PRODUTO.IDORCAMENTO = ORCAMENTO.IDORCAMENTO
		GROUP BY
			ITEM_PRODUTO.IDORCAMENTO) 
	) AS MEDIA		    
FROM
	ORCAMENTO;


/* QUESTÃO 15*/
SELECT
	YEAR(DT_ORCAMENTO)
    , MONTH(DT_ORCAMENTO)
	, COUNT(ORCAMENTO.IDORCAMENTO)
	, SUM(
		(SELECT 
			SUM(ITEM_SERVICO.QTDE * SERVICO.VALOR) AS TOTAL
		FROM
			ITEM_SERVICO
			INNER JOIN SERVICO ON
			SERVICO.IDSERVICO = ITEM_SERVICO.IDSERVICO
		WHERE 
			ITEM_SERVICO.IDORCAMENTO = ORCAMENTO.IDORCAMENTO
		GROUP BY
			ITEM_SERVICO.IDORCAMENTO)
	+ 	(SELECT 
			SUM(ITEM_PRODUTO.QTDE * PRODUTO.VALOR) AS TOTAL
		FROM
			ITEM_PRODUTO
			INNER JOIN PRODUTO ON
			PRODUTO.IDPRODUTO = ITEM_PRODUTO.IDPRODUTO
		WHERE 
			ITEM_PRODUTO.IDORCAMENTO = ORCAMENTO.IDORCAMENTO
		GROUP BY
			ITEM_PRODUTO.IDORCAMENTO) 
	) AS MEDIA		    
FROM
		ORCAMENTO
GROUP BY
	YEAR(DT_ORCAMENTO), MONTH(DT_ORCAMENTO);